# Copyright (c) 21.04.2026 Thomas Zierer
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

# These queries will get executed after the load and prior to alter

# Add artists which lack in data dump
Artist.1=INSERT INTO Artist (id, name) VALUES (355, 'Unknown Artist')
Artist.2=INSERT INTO Artist (id, name) VALUES (118760, 'No Artist')

# Resolve inconsitencies: Aliases which refer to a non-existing artist
# Do not remove the grouping: There are aliases with identical id but different writings
artist_aliases_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT aa.id, MIN(aa.name) AS name FROM artist_aliases_all aa GROUP BY aa.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_aliases_all.2=DROP TABLE artist_aliases_all

# Dito for groups
artist_groups_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT ag.id, MIN(ag.name) AS name FROM artist_groups_all ag GROUP BY ag.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_groups_all.2=DROP TABLE artist_groups_all

# Dito for members
artist_members_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT am.id, MIN(am.name) AS name FROM artist_members_all am GROUP BY am.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_members_all.2=DROP TABLE artist_members_all

# Label which refer to a non-existing parent label
Label=UPDATE Label l \
SET parentLabel_id = NULL \
WHERE l.parentLabel_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Label l0 WHERE l.parentLabel_id = l0.id \
)

# Setup genres & styles
Master_Genre=MERGE INTO Genre AS t \
USING (SELECT DISTINCT genres_id AS id FROM Master_Genre) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

Master_Style=MERGE INTO Style AS t \
USING (SELECT DISTINCT styles_id AS id FROM Master_Style) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

# Add artist which are referenced in master dump but lack in artist dump
# Usually empty but it doesn't hurt either
artist_master_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT ama.id, MIN(ama.name) AS name FROM artist_master_all ama GROUP BY ama.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_master_all.2=DROP TABLE artist_master_all

# Remove references to non-existing masters & serieses
Release.1=UPDATE Release r \
SET master_id = NULL \
WHERE r.master_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Master m WHERE r.master_id = m.id \
)
Release.2=UPDATE Release r \
SET series_id = NULL \
WHERE r.series_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Series s WHERE r.series_id = s.id \
)

# Enhance genres & styles
Release_Genre=MERGE INTO Genre AS t \
USING (SELECT DISTINCT genres_id AS id FROM Release_Genre) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

Release_Style=MERGE INTO Style AS t \
USING (SELECT DISTINCT styles_id AS id FROM Release_Style) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

# Remove references to non-existing labels
Release_labels=DELETE FROM Release_labels rl \
WHERE NOT EXISTS ( \
SELECT 1 FROM Label l WHERE rl.labels_KEY = l.id \
)

# Enhance artists
artist_release_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT ara.id, MIN(ara.name) AS name FROM artist_release_all ara GROUP BY ara.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_all.2=DROP TABLE artist_release_all

artist_release_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT area.id, MIN(area.name) AS name FROM artist_release_extraartist_all area GROUP BY area.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_extraartist_all.2=DROP TABLE artist_release_extraartist_all

# Build up ExtraArtist.
release_extraartist=MERGE INTO ExtraArtist AS t \
USING (SELECT DISTINCT artist_id, role_id FROM release_extraartist) AS s \
ON s.artist_id = t.artist_id AND s.role_id = t.role \
WHEN NOT MATCHED THEN INSERT (artist_id,role) VALUES (s.artist_id,s.role_id)

# Enhance Artist with tracks artists
artist_release_track_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT arta.id, MIN(arta.name) AS name FROM artist_release_track_all arta GROUP BY arta.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_track_all.2=DROP TABLE artist_release_track_all

# Enhance Artist with tracks ExtraArtist
artist_release_track_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT artea.id, MIN(artea.name) AS name FROM artist_release_track_extraartist_all artea GROUP BY artea.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_track_extraartist_all.2=DROP TABLE artist_release_track_extraartist_all

Track_ExtraArtist=MERGE INTO ExtraArtist AS t \
USING (SELECT DISTINCT extraArtists_artist_id AS artist_id, extraArtists_role AS role FROM Track_ExtraArtist) AS s \
ON s.artist_id = t.artist_id AND s.role = t.role \
WHEN NOT MATCHED THEN INSERT (artist_id,role) VALUES (s.artist_id,s.role)

artist_release_subtrack_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT DISTINCT arsea.id, MIN(arsea.name) AS name FROM artist_release_subtrack_extraartist_all arsea GROUP BY arsea.id) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_subtrack_extraartist_all.2=DROP TABLE artist_release_subtrack_extraartist_all

SubTrack_ExtraArtist=MERGE INTO ExtraArtist AS t \
USING (SELECT DISTINCT extraArtists_artist_id AS artist_id, extraArtists_role AS role FROM SubTrack_ExtraArtist) AS s \
ON s.artist_id = t.artist_id AND s.role = t.ROLE \
WHEN NOT MATCHED THEN INSERT (artist_id,role) VALUES (s.artist_id,s.role)

