# Copyright (c) 21.04.2026 Thomas Zierer
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

# These queries will get executed after the load and prior to alter

# Add artists which lack in data dump
Artist.1=DELETE FROM Artist WHERE id IN (355, 118760)
Artist.2=INSERT INTO Artist (id, name) VALUES (355, 'Unknown Artist')
Artist.3=INSERT INTO Artist (id, name) VALUES (118760, 'No Artist')
# Resolve inconsitencies: Aliases, groups, member which refer to a non-existing artist, 
# artists only contained in master/release dump 
Artist.4=MERGE INTO Artist AS t \
USING (SELECT aa.id, aa.name FROM artist_artist_all aa) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
Artist.5=DROP TABLE artist_artist_all
Artist.6=MERGE INTO Artist AS t \
USING (SELECT am.id, am.name FROM artist_master_all am) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
Artist.7=DROP TABLE artist_master_all
Artist.8=MERGE INTO Artist AS t \
USING (SELECT ar.id, ar.name FROM artist_release_all ar) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
Artist.9=DROP TABLE artist_release_all

# Labels which refer to a non-existing parent label
# and add referenced non-existing labels
Label.1=MERGE INTO Label AS t \
USING (SELECT lla.id, lla.name FROM label_label_all lla) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
Label.2=DROP TABLE label_label_all
Label.3=MERGE INTO Label AS t \
USING (SELECT lra.id, lra.name FROM label_release_all lra) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
Label.4=DROP TABLE label_release_all

# Setup genres & styles
Master_Genre.1=DELETE FROM Genre
Master_Genre.2=INSERT INTO Genre (id) \
SELECT DISTINCT mg.genres_id FROM Master_Genre mg \
UNION \
SELECT DISTINCT rg.genres_id FROM Release_Genre rg \

Master_Style.1=DELETE FROM Style
Master_Style.2=INSERT INTO Style (id) \
SELECT DISTINCT ms.styles_id FROM Master_Style ms \
UNION \
SELECT DISTINCT rs.styles_id FROM Release_Style rs \

# Remove references to non-existing masters
Release.1=UPDATE Release r \
SET master_id = NULL \
WHERE r.master_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Master m WHERE r.master_id = m.id \
)

Release.2=UPDATE Release r \
SET series_id = NULL \
WHERE r.series_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Series s WHERE r.series_id = s.id \
)

Format=UPDATE format_gen SET next_val = \
(SELECT MAX(id) + 1 FROM Format) \
WHERE sequence_name = 'Format'

# Build up ExtraArtist. Use INSERT as the table is empty and it's faster than MERGE
ExtraArtist.1=DELETE FROM ExtraArtist
ExtraArtist.2=INSERT INTO ExtraArtist (role,artist_id) \
(SELECT DISTINCT rea.role_id, rea.artist_id FROM ReleaseExtraartist rea \
UNION \
SELECT DISTINCT extraArtists_role, extraArtists_artist_id FROM Track_ExtraArtist \
UNION \
SELECT DISTINCT extraArtists_role,extraArtists_artist_id FROM SubTrack_ExtraArtist )

