# Copyright (c) 21.04.2026 Thomas Zierer
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

# These queries will get executed after the load and prior to alter

# Add artists which lack in data dump
Artist.1=INSERT INTO Artist (id, name) VALUES (355, 'Unknown Artist')
Artist.2=INSERT INTO Artist (id, name) VALUES (118760, 'No Artist')

# Resolve inconsitencies: Aliases which refer to a non-existing artist
artist_aliases_all.1=MERGE INTO Artist AS t \
USING (SELECT aa.id, aa.name FROM artist_aliases_all aa) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_aliases_all.2=DROP TABLE artist_aliases_all

# Dito for groups
artist_groups_all.1=MERGE INTO Artist AS t \
USING (SELECT ag.id, ag.name FROM artist_groups_all ag) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_groups_all.2=DROP TABLE artist_groups_all

# Dito for members
artist_members_all.1=MERGE INTO Artist AS t \
USING (SELECT am.id, am.name FROM artist_members_all am) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_members_all.2=DROP TABLE artist_members_all

# Labels which refer to a non-existing parent label
Label=UPDATE Label l \
SET parentLabel_id = NULL \
WHERE l.parentLabel_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Label l0 WHERE l.parentLabel_id = l0.id \
)

# Setup genres & styles
Master_Genre=INSERT INTO Genre (id) \
SELECT DISTINCT mg.genres_id FROM Master_Genre mg

Master_Style=INSERT INTO Style (id) \
SELECT DISTINCT ms.styles_id FROM Master_Style ms

# Add artist which are referenced in master dump but lack in artist dump
# Usually empty but it doesn't hurt either
artist_master_all.1=MERGE INTO Artist AS t \
USING (SELECT ama.id, ama.name FROM artist_master_all ama) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_master_all.2=DROP TABLE artist_master_all

# Remove references to non-existing masters
Release=UPDATE Release r \
SET master_id = NULL \
WHERE r.master_id IS NOT NULL \
AND NOT EXISTS ( \
SELECT 1 FROM Master m WHERE r.master_id = m.id \
)

# Enhance genres & styles
Release_Genre=MERGE INTO Genre AS t \
USING (SELECT DISTINCT genres_id AS id FROM Release_Genre) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

Release_Style=MERGE INTO Style AS t \
USING (SELECT DISTINCT styles_id AS id FROM Release_Style) AS s \
ON s.id = t.id \
WHEN NOT MATCHED THEN INSERT (id) VALUES (s.id)

# Remove references to non-existing labels
Release_labels=DELETE FROM Release_labels rl \
WHERE NOT EXISTS ( \
SELECT 1 FROM Label l WHERE rl.labels_KEY = l.id \
)

# Enhance artists
artist_release_all.1=MERGE INTO Artist AS t \
USING (SELECT ara.id, ara.name FROM artist_release_all ara) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_all.2=DROP TABLE artist_release_all

artist_release_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT area.id, area.name FROM artist_release_extraartist_all area) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_extraartist_all.2=DROP TABLE artist_release_extraartist_all

# Build up ExtraArtist. Use INSERT, it's faster than MERGE (MERGE needes 10 h)
release_extraartist=INSERT INTO ExtraArtist (artist_id,role) \
SELECT DISTINCT rea.artist_id, rea.role_id FROM release_extraartist rea

# Enhance Artist with tracks artists
artist_release_track_all.1=MERGE INTO Artist AS t \
USING (SELECT arta.id, arta.name FROM artist_release_track_all arta) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_track_all.2=DROP TABLE artist_release_track_all

# Enhance Artist with tracks ExtraArtist
artist_release_track_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT artea.id, artea.name FROM artist_release_track_extraartist_all artea) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_track_extraartist_all.2=DROP TABLE artist_release_track_extraartist_all

Track_ExtraArtist=MERGE INTO ExtraArtist AS t \
USING (SELECT DISTINCT extraArtists_artist_id, extraArtists_role FROM Track_ExtraArtist) AS s \
ON s.extraArtists_artist_id = t.artist_id AND s.extraArtists_role = t.role \
WHEN NOT MATCHED THEN INSERT (artist_id,role) VALUES (s.extraArtists_artist_id,s.extraArtists_role)

artist_release_subtrack_extraartist_all.1=MERGE INTO Artist AS t \
USING (SELECT arsea.id, arsea.name FROM artist_release_subtrack_extraartist_all arsea) AS s \
ON t.id = s.id \
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (s.id, s.name)
artist_release_subtrack_extraartist_all.2=DROP TABLE artist_release_subtrack_extraartist_all

SubTrack_ExtraArtist=MERGE INTO ExtraArtist AS t \
USING (SELECT DISTINCT extraArtists_artist_id, extraArtists_role FROM SubTrack_ExtraArtist) AS s \
ON s.extraArtists_artist_id = t.artist_id AND s.extraArtists_role = t.ROLE \
WHEN NOT MATCHED THEN INSERT (artist_id,role) VALUES (s.extraArtists_artist_id,s.extraArtists_role)

